wide: ubuntu_white-orange(cof)_hex_su.svg
	inkscape -f '$<' -C -w 310 -h 150 -e Wide310x150Logo.scale-100.png
	inkscape -f '$<' -C -w 388 -h 188 -e Wide310x150Logo.scale-125.png
	inkscape -f '$<' -C -w 465 -h 225 -e Wide310x150Logo.scale-150.png
	inkscape -f '$<' -C -w 620 -h 300 -e Wide310x150Logo.scale-200.png
	inkscape -f '$<' -C -w 1240 -h 600 -e Wide310x150Logo.scale-400.png
